blogapp/blogapp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

from django.contrib import admin

from accounts.views import (login_view, register_view, logout_view)
# from rest_framework_jwt.views import obtain_jwt_token
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^comments/', include("comments.urls", namespace='comments')),
    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^', include("posts.urls", namespace='posts')),
    # url(r'^api/auth/token/', obtain_jwt_token),
    url(r'^api/comments/', include("comments.api.urls", namespace='comments-api')),
    url(r'^api/posts/', include("posts.api.urls", namespace='posts-api')),
    url(r'^api/accounts/', include("accounts.api.urls", namespace='accounts-api')),

    #url(r'^posts/$', views.post_home),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/posts/api/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views



urlpatterns = [
    url(r'^$', views.PostListAPIView.as_view(), name='list'),
    url(r'^create/$', views.PostCreateAPIView.as_view(), name='create'),

    #url(r'^(?P<pk>\d+)/$', views.PostCreateAPIView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/$', views.PostDetailAPIView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit$', views.PostUpdateAPIView.as_view(), name='update'),
    url(r'^(?P<slug>[\w-]+)/delete$', views.PostDeleteAPIView.as_view(), name='delete'),

]

blogapp/posts/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views
# from .views import (
#     post_list,
#     post_create,
#     post_detail,
#     post_update,
#     post_delete,
# )


urlpatterns = [
    url(r'^$', views.post_list, name='list'),
    url(r'^create/$', views.post_create),
    url(r'^(?P<slug>[\w-]+)/$', views.post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.post_delete),
    #url(r'^posts/$', views.post_home),
]

blogapp/comments/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

# Create your models here.

class CommentManager(models.Manager):
    def all(self):
        qs = super(CommentManager, self).filter(parent=None)
        return qs
    def filter_by_instance(self, instance):
        content_type = ContentType.objects.get_for_model(instance.__class__) # (Post)
        obj_id = instance.id
        qs = super(CommentManager, self).filter(content_type=content_type, object_id=obj_id).filter(parent=None)
        #super(CommentManager, self) equals to Comment.objects, add objects = CommentManager()
        return qs

    def create_by_model_type(self, model_type, slug, content, user, parent_obj=None):
        model_qs = ContentType.objects.filter(model=model_type)
        if model_qs.exists():
            SomeModel = model_qs.first().model_class()
            obj_qs = SomeModel.objects.filter(slug=slug)
            if obj_qs.exists() and obj_qs.count() == 1:
                instance = self.model()
                instance.content = content
                instance.user = user
                instance.content_type = model_qs.first()
                instance.object_id = obj_qs.first().id
                if parent_obj:
                    instance.parent = parent_obj
                instance.save()
                return instance
        return None


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    parent = models.ForeignKey("self", null=True, blank=True)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = CommentManager()

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return str(self.user.username)

    def get_absolute_url(self):
        return reverse("comments:comment_thread", kwargs={"id": self.id})

    def get_delete_url(self):
        return reverse("comments:comment_delete", kwargs={"id": self.id})


    def children(self): # replies
        return Comment.objects.filter(parent=self)

    @property
    def is_parent(self): #first reply
        if self.parent is not None:
            return False
        return True

blogapp/posts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.text import slugify
from django.utils.safestring import mark_safe
from django.conf import settings
from markdown_deux import markdown
from comments.models import Comment
from django.contrib.contenttypes.models import ContentType


from.utils import get_read_time
# Create your models here.

# Model View Controller

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        #Post.objects.all() = super(PostManager, self).all()
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    return "%s/%s" %(instance.id, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location,
                              null=True,
                              blank=True,
                              width_field="width_field",
                              height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    read_time = models.TimeField(null=True, blank=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})  #{% url 'posts:detail' id=obj.id %}

    def get_api_url(self):
        return reverse("posts-api:detail", kwargs={"slug": self.slug})  # {% url 'posts:detail' id=obj.id %}


    class Meta:
        ordering = ["-timestamp", "-updated"]

    def get_html(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)

    @property  # instance.comments // instance.comments()
    def comments(self):
        qs = Comment.objects.filter_by_instance(self)
        return qs

    @property
    def get_content_type(self):
        content_type = ContentType.objects.get_for_model(self.__class__)
        return content_type


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_html()
        read_time_var = get_read_time(html_string)
        instance.read_time = read_time_var

# def pre_save_post_receiver(sender, instance, *args, **kwargs):
#     slug = slugify(instance.title)
#
#     exists = Post.objects.filter(slug=slug).exists()
#     if exists:
#         slug = "%s-%s" % (slug, instance.id)
#         instance.slug = slug

pre_save.connect(pre_save_post_receiver, sender=Post)

blogapp/posts/api/views.py
from django.db.models import Q
from rest_framework.filters import (
                                    SearchFilter,
                                    OrderingFilter,
                                    )
from rest_framework.generics import (
                                    CreateAPIView,
                                    ListAPIView,
                                    RetrieveAPIView,
                                    UpdateAPIView,
                                    DestroyAPIView,
                                    RetrieveUpdateAPIView,
                                    )

from posts.models import Post
from .pagination import PostLimitOffsetPagination, PostPageNumberPagination
from .permissions import IsOwnerOrReadOnly

from rest_framework.pagination import (
                                        LimitOffsetPagination,
                                        PageNumberPagination,
                                        )

from rest_framework.permissions import (
                                        AllowAny,
                                        IsAuthenticated,
                                        IsAdminUser,
                                        IsAuthenticatedOrReadOnly,
                                        )

from .serializers import (
                        PostCreateUpdateSerializer,
                        PostListSerializer,
                        PostDetailSerializer,
                        )


class PostCreateAPIView(CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    # lookup_url_kwarg = 'abc'
    permission_classes = [IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)



class PostDetailAPIView(RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    lookup_field = 'slug'
    # lookup_url_kwarg = 'abc'

class PostUpdateAPIView(RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    lookup_field = 'slug'
    # lookup_url_kwarg = 'abc'
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

    def perform_update(self, serializer):
        serializer.save(user=self.request.user)

class PostDeleteAPIView(DestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    lookup_field = 'slug'
    # lookup_url_kwarg = 'abc'
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]




class PostListAPIView(ListAPIView):
    serializer_class = PostListSerializer
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ['title', 'content', 'user__first_name']
    pagination_class = PostPageNumberPagination #PostLimitOffsetPagination #PageNumberPagination

    def get_queryset(self, *args, **kwargs):
        # queryset_list = super(PostListAPIView, self).get_queryset(*args, **kwargs)
        queryset_list = Post.objects.all()
        query = self.request.GET.get("q")

        if query:
            queryset_list = queryset_list.filter(
                Q(title__icontains=query) |
                Q(content__icontains=query) |
                Q(user__first_name__icontains=query) |
                Q(user__last_name__icontains=query)
            ).distinct()

        return queryset_list

blogapp/posts/views.py
from urllib.parse import quote_plus

from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.utils import timezone
from django.db.models import Q
from comments.forms import CommentForm
from comments.models import Comment

from .forms import PostForm
from .models import Post
from .utils import get_read_time


def post_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    # if not request.is_authenticated():
    #     raise Http404

    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()

        messages.success(request, "Successfully Created")
        return HttpResponseRedirect(instance.get_absolute_url())
    # if request.method =="POST":
    #     print(request.POST.get("content"))
    #     print(request.POST.get("title"))
    #
    context = {
        "form": form,
    }
    return render(request, "post_form.html", context)

def post_detail(request, slug=None):
    #instance = Post.objects.get(id=2)
    instance = get_object_or_404(Post, slug=slug) #title="Post 3"
    if instance.draft or instance.publish > timezone.now().date():
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    share_string = quote_plus(instance.content)


    print(get_read_time(instance.get_html()))
    # dont need these since i added CommentManager in models.py
    # content_type = ContentType.objects.get_for_model(Post)
    # obj_id = instance.id
    initial_data = {
        "content_type": instance.get_content_type,
        "object_id": instance.id
    }

    comment_form = CommentForm(request.POST or None, initial=initial_data)
    if comment_form.is_valid() and request.user.is_authenticated():
        c_type = comment_form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=c_type)
        obj_id = comment_form.cleaned_data.get("object_id")
        content_data = comment_form.cleaned_data.get("content")
        parent_obj = None
        try:
            parent_id = int(request.POST.get("parent_id"))
        except:
            parent_id = None
        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists():
                parent_obj = parent_qs.first()
        new_comment, created = Comment.objects.get_or_create(
                                    user = request.user,
                                    content_type = content_type,
                                    object_id = obj_id,
                                    content = content_data,
                                    parent = parent_obj,
                                )
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url()) # this will update the form after commenting.


    comments = instance.comments # Comment.objects.filter_by_instance(instance)


    context = {
        "title": instance.title,
        "instance": instance,
        "share_string": share_string,
        "comments": comments,
        "comment_form": comment_form,
    }
    return render(request, "post_detail.html", context)

def post_list(request): # list items
    # if request.user.is_authenticated():
    #     context = {
    #         "title": "My User List"
    #     }
    # else:
    #     context = {
    #         "title": "List"
    #     }
    today = timezone.now().date()
    queryset_list = Post.objects.active()
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.objects.all()

    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(user__first_name__icontains=query) |
            Q(user__last_name__icontains=query)
        ).distinct()
    paginator = Paginator(queryset_list, 3)  # Show 25 contacts per page
    page_request_var = "page"
    page = request.GET.get(page_request_var)

    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)

    context = {
        "object_list" : queryset,
        "title": "List",
        "page_request_var": page_request_var,
        "today": today,
    }
    return render(request, "post_list.html", context)


def post_update(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance = instance)  #instance = instance ; it adds original data to edit form
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()

        messages.success(request, "Successfully Updated", extra_tags="some-tag")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "title": instance.title,
        "instance": instance,
        "form": form,
    }
    return render(request, "post_form.html", context)


def post_delete(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    messages.success(request, "Successfully Updated", extra_tags="some-tag")
    return redirect("posts:list")

blogapp/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %}Try Django 1.9{% endblock head_title%}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' >

    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
    <style>
        {% block style %} {% endblock style %}
    </style>

    {% block head_extra %} {% endblock head_extra %}
</head>
<body>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.1';
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>


    {% include "messages_display.html" %}

    <div class="container">
        <ol class="breadcrumb">
            <li><a href="{% url 'posts:list' %}">Home</a></li>

            {% block post_detail_link %}
            {% endblock %}

            {% if not request.user.is_authenticated %}
            <li class="pull-right"><a href="{% url 'register' %}">Register</a></li>
            <li class="pull-right"><a href="{% url 'login' %}">Login</a></li>
            {% else %}
            <li class="pull-right"><a href="{% url 'logout' %}">Logout</a></li>
            {% endif %}
        </ol>
        {% block content %}
        {% endblock content %}
    </div>


<!-- Latest compiled and minified JavaScript -->
<script   src="http://code.jquery.com/jquery-1.12.2.min.js"   integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="   crossorigin="anonymous"></script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js'></script>

<script type="text/javascript">
    $(document).ready(function() {
        $(".content-markdown").each(function() {
            var content = $(this).text()
            var markedContent = marked(content)
            $(this).html(markedContent)
        })

        $(".post-detail-img img").each(function() {
            $(this).addClass("img-fluid")
        })

        var titleInput = $("#id_title")  //when django runs the form, it adds "id_" in front of the field name. ex id_title, id_content, id_image etc
        //$("#preview-title").text(titleInput.val())

        var contentInput = $("#id_content")
        //$("#preview-content").html(marked(contentInput.val()))


        //
        function setContent(value) {
            var markedContent = marked(value)
            $("#preview-content").html(markedContent)
            $("#preview-content img").each(function() {
                $(this).addClass("img-fluid")
            })
        }
        setContent(contentInput.val())
        contentInput.keyup(function() {
            //console.log($(this).val())
            var newContent = $(this).val()
            setContent(newContent)
        })

        function setTitle(value) {
            $("#preview-title").text(value)
        }
        setTitle(titleInput.val())

        titleInput.keyup(function() {
            console.log($(this).val());
            var newTitle = $(this).val()
            setTitle(newTitle)
        })

        $(".comment-reply-btn").click(function(event) {
            event.preventDefault();
            $(this).parent().next(".comment-reply").fadeToggle();
        })

    })



</script>
</body>


</html>

blogapp/templates/comment_thread.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}
{% block head_title %}
    {{ instance.title }} | {{ block.super }}
{% endblock head_title%}

<style>
    {% block style %}
    h1 {
        color: #777777;
    }
    {% endblock style %}
</style>

{% block content %}



<div class="col-sm-6 col-sm-offset-3">


        <p>{{ comment.content }}</p>
    <footer>via {{ comment.user }} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %} {{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %} | {% endif %} {% if request.user == comment.user %}<a href="{{ comment.get_delete_url }}">Delete {% endif %}</a></footer>
        <div>
            <hr/>
            {% for child_comment in comment.children %}
            <blockquote>
                <p>{{ child_comment.content }}</p>
                <footer>via {{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago |  {% if request.user == child_comment.user %}<a href="{{ child_comment.get_delete_url }}">Delete</a>  {% endif %}</footer>

            </blockquote>
            {% endfor %}

        {% if request.user.is_authenticated %}
        <form method="POST" action="."> {% csrf_token %}
            {{ form |crispy }}
            <input type="hidden" name="parent_id" value="{{ comment.id }}">
            <input type="submit" value="Reply" class="btn btn-default">
        </form>
        {% else %}
        <hr/>
        <p>You must login to comment</p>
        {% endif %}
        </div>
    <hr/>

</div>
{% endblock content %}

blogapp/templates/confirm_delete.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}
{% block head_title %}
    {{ instance.title }} | {{ block.super }}
{% endblock head_title%}

<style>
    {% block style %}
    h1 {
        color: #777777;
    }
    {% endblock style %}
</style>

{% block content %}



<div class="col-sm-6 col-sm-offset-3">


        <form method="POST" action="."> {% csrf_token %}
            <p>Are you sure you want to delete: "{{ object.content }}"? </p>



            <input type="submit" value="Delete" class="btn btn-warning">
            <a href="{{ object.get_absolute_url }}" class="btn btn-default">Cancel</a>
        </form>
    <hr/>

</div>
{% endblock content %}

blogapp/templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}



<div class="col-sm-6 col-sm-offset-3">
    <h1>{{ title }}</h1>

    <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
        {{ form | crispy }}
        <input type="submit" class="btn btn-default" value="{{ title }}" />
    </form>
</div>

{% endblock content %}

blogapp/templates/messages_display.html
{% if messages %}
    <div class="messages">
        <ul class="messages">
            {% for msg in messages %}
            <li{% if msg.tags %} class="{{ msg.tags }}"{% endif %}>{{ msg }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

blogapp/templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}
{% block head_title %}
    {{ instance.title }} | {{ block.super }}
{% endblock head_title%}


{% block post_detail_link %}
    <li><a href="{{ instance.get_absolute_url }}">{{ instance.title }}</a></li>
{% endblock %}
<style>
    {% block style %}
    h1 {
        color: #777777;
    }
    {% endblock style %}
</style>

{% block content %}
<div class="col-sm-6 col-sm-offset-3">
    {% if instance.image %}
        <img src="{{ instance.image.url }}" class="img-fluid"/>
    {% endif %}

    <h1>{{ title }} <small>{% if instance.draft %} <span style="color:red;">Draft</span> {% endif %}{{ instance.publish }}</small></h1>

    <p>Read time: {{ instance.read_time | time:"i"}} minutes</p>

    {% if instance.user.get_full_name %}
    <p>Author: {{ instance.user.get_full_name }}</p>
    {% endif %}
    <!-- {{ instance.content|urlify }}<br/>
    {{ share_string }}<br/> -->

    <!--<a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">-->
        <!--Share on Facebook-->
    <!--</a>-->
    <!--<a href="https://twitter.com/h  ome?status={{ instance.content|urlify }}%20{{ request.build_absolute_uri }}">-->
    <!--Share on Twitter-->
    <!--</a>-->

    <!--<a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'>Share on Google+</a>-->
    <div class="row">
        <div class="col-sm-12">
            <hr/>
            <br/>
            <div class="post-detail-img">{{ instance.get_html }}<br/></div>
            <!--{{ instance.comments.all }}-->
            <hr/>
            <br/>

            <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="box_count" data-action="like" data-size="small" data-show-faces="true" data-share="false"></div>
            <div>
                <p class="lead">Comments</p>
                {% if request.user.is_authenticated %}
                <form method="POST" action="."> {% csrf_token %}
                    {{ comment_form|crispy }}
                    <input type="submit" value="Post Comment" class="btn btn-default">
                </form>
                {% else %}
                <hr/>
                <p>You must login to comment</p>
                {% endif %}


                {% for comment in comments %}
                    <blockquote>
                        <p>{{ comment.content }}</p>
                        <footer>via {{ comment.user }} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %} {{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %} | {% endif %}<a class="comment-reply-btn" href="#">Reply</a> |     <a class="" href="{{ comment.get_absolute_url }}">Thread</a></footer>
                        <div class="comment-reply" style="display:none;">
                            {% for child_comment in comment.children %}
                                <blockquote>
                                    <p>{{ child_comment.content }}</p>
                                    <footer>via {{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago</footer>
                                </blockquote>
                            {% endfor %}

                        {% if request.user.is_authenticated %}

                        <form method="POST" action="."> {% csrf_token %}
                            {{ comment_form|crispy }}
                            <input type="hidden" name="parent_id" value="{{ comment.id }}">
                            <input type="submit" value="Reply" class="btn btn-default">
                        </form>
                        {% else %}
                        <hr/>
                        <p>You must login to comment</p>
                        {% endif %}
                        </div>
                    </blockquote>
                    <hr/>
                {% endfor %}

                <!--{{ instance.comment_set.all }}-->
            </div>
            <!--<div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5"></div>-->
        </div>
    </div>
</div>
{% endblock content %}

blogapp/templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_extra %}
    {{ form.media }}
{% endblock head_extra %}

{% block content %}



<div class="col-sm-6">
    <h1>FORM</h1>

    <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
        {{ form | crispy }}
        <input type="submit" class="btn btn-default" value="Create Post" />
    </form>
</div>
<div class="col-sm-6">
    <h1>Preview</h1>
    <div class="content-preview">
        <h3 id="preview-title"></h3>
        <p id="preview-content"></p>
    </div>
</div>
{% endblock content %}